# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sonniesedge
email: charlie@sonniesedge.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Sonniesedge writes things for the love of it.
twitter_username: sonniesedge
github_username:  sonniesedge
