baseURL = "http://45.33.90.186"
languageCode = "en-gb"
title = "sonniesedge"
theme = "sonniesedge"
pluralizeListTitles = "false"
pygmentsuseclasses = "true"
PygmentsCodeFences = "true"

SectionPagesMenu = "main"
googleAnalytics = "UA-123-45"
paginate = 100
